
--------> Part_4 TestingAPI

CREATE TABLE testing_reports_table (
				TESTING_REPORT_ID INT AUTO_INCREMENT,
				SITE_ID INT,
				USER_NAME VARCHAR(225),       

				CREATED_DATE DATETIME,
				CONSTRAINT PK_TESTING_REPORT_ID PRIMARY KEY(TESTING_REPORT_ID)
              
);


CREATE TABLE testing_table (

				TESTING_ID INT AUTO_INCREMENT,
				TESTING_REPORT_ID INT,
				LOCATION_NUMBER INT,
                LOCATION_NAME VARCHAR(225),
 				TEST_ENGINEER_NAME VARCHAR(225),
				DATE VARCHAR(225),
				DETAILS_TEST_INSTRUMENT VARCHAR(225),
				CONTINUITY VARCHAR(225),
				INSULATION_RESISANCE VARCHAR(225),
				IMPEDANCE VARCHAR(225),
				RCD VARCHAR(225),
				EARTH_ELECTRODE_RESISTANCE VARCHAR(225),
				DESIGNATION  VARCHAR(225),
				COMPANY_NAME  VARCHAR(225),        

 				CONSTRAINT PK_TESTING_ID PRIMARY KEY(TESTING_ID),
				CONSTRAINT FK_DISTRIBUTION_TESTING_REPORT_ID FOREIGN KEY (TESTING_REPORT_ID) REFERENCES TESTING_REPORTS_TABLE(TESTING_REPORT_ID) ON DELETE CASCADE 
               
);

CREATE TABLE testing_distribution_table (

                DISTRIBUTION_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
                DISTRIBUTION_BOARD_DETAILS VARCHAR(225),
				REFERANCE VARCHAR(225),
				LOCATION VARCHAR(225),
				CORRECT_SUPPLY_POLARITY VARCHAR(225),
				NUM_OUTPUT_CIRCUITS_USE VARCHAR(225),
				RATINGS_AMPS VARCHAR(225),
				NUM_OUTPUT_CIRCUITS_SPARE VARCHAR(225),
				INSTALLED_EQUIPMENT_VULNARABLE  VARCHAR(225),
				INCOMING_VOLTAGE VARCHAR(225),
				INCOMING_ZS VARCHAR(225),
				INCOMING_IPF VARCHAR(225),
				CONSTRAINT PK_TESTING_DISTRIBUTION_ID PRIMARY KEY(DISTRIBUTION_ID),
				CONSTRAINT FK_DISTRIBUTION_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE     

				
	);

CREATE TABLE testing_records_table ( 
                TESTING_RECORD_ID INT AUTO_INCREMENT,
				TESTING_ID INT,
 				CIRCUIT_NO VARCHAR(225),
				CIRCUIT_DESC  VARCHAR(225),
				CIRCUIT_STANDARD_NO  VARCHAR(225),
				CIRCUIT_TYPE  VARCHAR(225), 
				CIRCUIT_RATING VARCHAR(225), 
				CIRCUIT_BREAKING_CAPACITY VARCHAR(225),
				CONDUCTOR_INSTALLATION VARCHAR(225),
				CONDUCTOR_LIVE VARCHAR(225),
				CONDUCTOR_PECPC VARCHAR(225),
				CONTINUTIY_APPROXIMATELENGTH VARCHAR(225),
				CONTINUTIY_R1_R2 VARCHAR(225),
				CONTINUTIY_R2 VARCHAR(225),
				CONTINUTIY_LL VARCHAR(225),
				CONTINUTIY_LE VARCHAR(225),
				CONTINUTIY_POLARITY VARCHAR(225),
				TEST_VOLTAGE VARCHAR(225),
				TEST_LOOPIMPEDANCE VARCHAR(225),
				TEST_FAULTCURRENT VARCHAR(225),
				DISCONNECTION_TIME VARCHAR(225),
				 
				RCD_CURRENT VARCHAR(225),
				RCD_OPERATINGCURRENT VARCHAR(225),
				RCD_OPERATINGFIVECURRENT VARCHAR(225),
				RCD_TESTBUTTONOPERATION VARCHAR(225),
				RCD_REMARKS VARCHAR(225),
					
				CONSTRAINT PK_TESTING_RECORD_ID PRIMARY KEY(TESTING_RECORD_ID),
				CONSTRAINT FK_TESTING_ID FOREIGN KEY (TESTING_ID) REFERENCES TESTING_TABLE(TESTING_ID) ON DELETE CASCADE              

 );